/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import psychiatric.Psychiatric;

public class Window extends javax.swing.JPanel implements Runnable{
    
    private Thread thread;
    private Psychiatric pyschiatric;
    private MouseEvent click;
    
    //CAPTURE EVENTS
    private ArrayList<Integer> keys = new ArrayList<>();
    
    public Window(){
        initComponents();
        this.setPreferredSize(new Dimension(1000, 900));
        this.setDoubleBuffered(true);
        this.setFocusable(true); //?
    }
    
    public void setPyschiatric(Psychiatric pyschiatric) {
        this.pyschiatric = pyschiatric;
        thread = new Thread(this);
        thread.start();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        pyschiatric.draw(g2);
        g2.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(!keys.contains(evt.getKeyCode())){
            keys.add(evt.getKeyCode()); 
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        keys.remove(Integer.valueOf(evt.getKeyCode()));
    }//GEN-LAST:event_formKeyReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        click = evt;
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        click = null;
    }//GEN-LAST:event_formMouseReleased

    @Override
    public void run() {
        double interval = 1000000000/60;
        double delta = 0;
        long lastTime = System.nanoTime();
        long actualTime;
        
        while(true){
            actualTime = System.nanoTime();
            delta += (actualTime-lastTime)/interval;
            lastTime = actualTime;
            
            if(delta >= 1){
                pyschiatric.keyPressed(keys);
                if(click != null){
                    pyschiatric.mousePressed(click.getButton(), click.getX(), click.getY());
                }
                repaint();
                delta--;
            }
            try {
                Thread.sleep(5);
            } catch (InterruptedException ex) {
            }
        }
    }
    
    public static void main(String[] args) {
        
        //CREATE WINDOW
        JFrame window = new JFrame();
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setResizable(false);
        
        //PANEL
        Window panel = new Window();
        window.add(panel); 
        window.pack(); //SIZE
        
        //ADD PSYCHIATRIC
        Psychiatric pyschiatric = new Psychiatric();
        panel.setPyschiatric(pyschiatric);
        
        //START
        window.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
